apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0

          ports:
            - containerPort: 3000
              name: http

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
              subPath: dashboard.yaml

            - name: dashboard
              mountPath: /var/lib/grafana/dashboards/devops-commission-dashboard.json
              subPath: devops-commission-dashboard.json

          resources:
            requests:
              cpu: 50m
              memory: 128Mi

            limits:
              cpu: 300m
              memory: 384Mi

      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboard
          configMap:
            name: grafana-dashboard
